### ISSUE TITLE
What is the 'BioMedGPT'？

### ISSUE THREAD

**Issue by Qing1Zhong** [BioFM/OpenBioMed#17]
Really appreciate your work! However, I noticed two papers referenced in the documentation, one being **_"Empowering AI drug discovery with explicit and implicit knowledge"_**, and the other "**_Large-Scale Cell Representation Learning via Divide-and-Conquer Contrastive Learning_**"(CellLM). Neither of these papers seem to mention BioMedGPT. Could you provide a link to the paper on BioMedGPT?

**Comment by icycookies** [comment]
Thank you for your interest in BioMedGPT! We appreciate your attention. However, please note that we are still in the process of releasing the BioMedGPT paper. In the meantime, you can refer to the project ***OpenBioMed_project*** when citing BioMedGPT

**Comment by Qing1Zhong** [comment]
Looking forward to your paper!!!🥺🥺🥺🥺🥺🥺
