### ISSUE TITLE
gene2vec file for CellLM model

### ISSUE THREAD

**Issue by Tsinghua-gongjing** [BioFM/OpenBioMed#5]
Hi,

Thank you for releasing the beautiful work. The dataset and ckpt have been uploaded to Baidu cloud. Could you please also upload the gene2vec file for running CellLM?

Best

**Comment by BioFM** [comment]
Thanks,
We have upload the gene2vec file , you can download it from [here](https://pan.baidu.com/s/1iAMBkuoZnNAylhopP5OgEg), the password is 7a6b.
