### ISSUE TITLE
is there some examples for inference? 

### ISSUE THREAD

**Issue by qq7987590** [BioFM/OpenBioMed#9]
Hi, I've read the documentation before, and most of it is about training examples. 
Are there any inference examples? 
after I got BioMedGPT_1600M.pth file, 
how do I load the model, input a text, and get Molecule?

**Comment by BioFM** [comment]
Thank you for taking the time to explore BioMedGPT! We would like to inform you that at the moment, OpenBioMed exclusively offers fine-tuning pipelines for the model. For a quick evaluation of BioMedGPT on molecule-text cross retrieval, please refer to the documentation at docs/[mtr.md](http://mtr.md/) and open_biomed/tasks/multi_modal_tasks/mtr.py. Kindly note that we are working on making inference examples and zero-shot text-to-molecule or molecule-to-text generation available in our upcoming release. Thank you for your understanding and patience.
